<?php

/**
 * @file
 * Contains kgaut_tools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\StreamWrapper\PublicStream;

/**
 * Implements hook_help().
 */
function kgaut_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kgaut_tools module.
    case 'help.page.kgaut_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tools and services for drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 *
 * Generate all image styles once an Image is uploaded.
 * Tip by flocondetoile.
 *
 * @see http://flocondetoile.fr/blog/generer-des-styles-d-images-automatiquement-avec-drupal-8
 */
function kgaut_tools_entity_insert(EntityInterface $entity) {
  /** @var \Drupal\file\Entity\File $entity */
  if ($entity instanceof FileInterface) {
    $image = \Drupal::service('image.factory')->get($entity->getFileUri());
    /** @var \Drupal\Core\Image\Image $image */
    if ($image->isValid()) {
      $styles = ImageStyle::loadMultiple();
      $image_uri = $entity->getFileUri();
      /** @var \Drupal\image\Entity\ImageStyle $style */
      foreach ($styles as $style) {
        $destination = $style->buildUri($image_uri);
        $style->createDerivative($image_uri, $destination);
      }
    }
  }
}

/**
 * Implements hook_preprocess().
 *
 * Add custom variable to all templates.
 */
function kgaut_tools_preprocess(&$variables, $hook) {
  $variables['basepath'] = base_path();
  $variables['pathtotheme'] = base_path() . drupal_get_path('theme', 'funbreak_front');
  $variables['pathtotfiles'] = PublicStream::basePath();
}