field.formatter.settings.string_title:
  type: mapping
  label: Title formatter settings
  mapping:
    tag:
      type: string
      label: Tag

field.formatter.settings.link_button:
  type: mapping
  label: Button formatter settings
  mapping:
    label:
      type: string
      label: Button label
    classes:
      type: string
      label: Classes
