<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function kgaut_tools_paragraphs_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  $variables['type'] = (FALSE !== strpos($paragraph->bundle(), '_and_')) ? 'double' : 'simple';
}

function kgaut_tools_paragraphs_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  if (FALSE !== strpos($paragraph->bundle(), '_and_')) {
    $suggestions[] = 'paragraph__double';
  }
}
